import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App : CCAC01",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="h-screen flex flex-col">
          <Navbar />
            <div className="flex-grow">
              {children}
            </div>
          <footer className="p-3 bg-blue-200">Footer</footer>
        </div>
      </body>
    </html>
  );
}
